### ISSUE TITLE
Should the query back object be deepcopied before update it?

### ISSUE THREAD

**Issue by winterTTr** [programming-kubernetes/cnat#6]
Please see the line here:
https://github.com/programming-kubernetes/cnat/blob/33d5f465910a4c21b004390e05d60562b7f05168/cnat-client-go/controller.go#L228

The object is query back using:
https://github.com/programming-kubernetes/cnat/blob/33d5f465910a4c21b004390e05d60562b7f05168/cnat-client-go/controller.go#L214

So, should we call deep copy on this returned object and update it on the copied one?
When we should use the deep copy function that code-gen generated? I see official sample use the deep copy explicitly but there is no mentioned about this in your code.

**Comment by sttts** [comment]
Yes, it must be deepcopied. Lister object are owned by the lister. Great find!

**Comment by sttts** [comment]
@winterTTr  can you review https://github.com/programming-kubernetes/cnat/pull/7 ?

**Comment by winterTTr** [comment]
I check the changes, and it is good to merge without more comments. Thanks very much.

**Comment by winterTTr** [comment]
I check the changes, and it is good to merge without more comments. Thanks very much.
